spring:
  profiles:
    active: "local"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/workspace/h2/testdb
    username: sa
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher