spring:
  profiles:
    active: "local"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/workspace/h2/testdb
    username: sa
    driver-class-name: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop